<?php

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_bylawlist_ckeditor_plugin() {
  return array(
    'bylawlist' => array(
      'name' => 'bylawlist',
      'desc' => t('CKEditor Bylaw List Button'),
      'path' => libraries_get_path('bylawlist', TRUE) . '/',
      'buttons' => array(
        'Bylawlist' => array(
          /* 'icon' => 'icons/bylawlist.png', */
          'label' => t('Bylaw List'),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function ckeditor_bylawlist_libraries_info() {
  return array(
    'bylawlist' => array(
      'name' => 'CKEditor Bylaw List',
    ),
  );
}